#!/bin/sh



for tuname in blank `cat extra-users*`; do
    if [ "$tuname" = "blank" -o "$tuname" = "blank " ]; then
      tunamearg=""
    else
      tunamearg="-keyf=$tuname"
    fi

    echo ==============
    msg="user: $tuname"
    if echo '/quit' | ./oysttyer $tunamearg ; then
      echo "$msg status: OK"
    else
      echo "$msg status: BAD"
    fi
done
