#!/bin/sh

# Basic logic:
# for user2follow in uerj-related-users
#   for follower in extra-users or default user
#        make follower follow user2follow



# get all usernames, one per line, without @
# prepend the tags with /follow
# pass to oysttyer

# usuarios blacklisted
blacklist_ini="flamengo"

for tuname in `cat extra-users*` blank; do
  if [ "$tuname" = "blank" -o "$tuname" = "blank " ]; then
    tunamearg=""
  else
    tunamearg="-keyf=$tuname"
  fi
  
  if [ "$tuname" = "FDMouraNeto" ]; then
    blacklist="$blacklist_ini
    patriciassis"
  else
    blacklist="$blacklist_ini"
  fi

  set -x
  grep -E -o '@[A-Za-z0-9_-]+' /tmp/bla | sed 's/@/\/follow /g' | grep -v $blacklist| oysttyer $tunamearg &
  set +x
done


# Scratch:
#
# echo '/follow labmacambira' | oysttyer -keyf=uerj1999
