#!/bin/sh

#sed 's/\(#[A-Za-z0-9_-]*') \(#[A-Za-z0-9_-]*\)/tag/g' $*


sed -E "s/(#[A-Za-z0-9_-]*\ )+(#[A-Za-z0-9_-]*)$/`grep -E -o '(#[A-Za-z0-9_-]*\ )+(#[A-Za-z0-9_-]*)$' /tmp/mudar |xargs -n1 | gsort -R | xargs`/g"
