#!/bin/bash
#
#
# This will enter an infinite loop and tweet every x seconds
# a random line from tweets.txt
#
# If you want multiple accounts, put the extra users in the file extra-users,
# separated by space.


mysort=sort
if hash gsort 2>/dev/null; then
  mysort=gsort
fi

while true
do
  for tuname in blank `$mysort -R extra-users` ; do
    sleep 30
    line=`$mysort -R tweets.txt | head -n 1`
    randn=`seq 1 10000|$mysort -R |head -n 1`
    echo "x${tuname}x"
    if [ "$tuname" = "blank" -o "$tuname" = "blank " ]; then
      tunamearg=""
    else
      tunamearg="-keyf=$tuname"
    fi

    # randomize tag order
    msg=`randomize-tags $line`
    echo ORIG $line
    echo RNDO $msg
    
    msg="$msg #IPRJ$randn"
    extra_tag=`$mysort -R extra-tags | head -n 1`
    msg_extra_tags="$msg $extra_tag"
    msgsize=`echo $msg_extra_tags|wc -c`
    echo message size: $msgsize
    if [ "$msgsize" -lt 139 ]; then
      msg=$msg_extra_tags
    fi
    set -x
    oysttyer $tunamearg -status="$msg" &
    set +x
  done
#  nsec=`seq 60 260|$mysort -R |head -n 1`
#  nsec=`seq 30 120|$mysort -R |head -n 1`
#  nsec=`seq 500 3000|$mysort -R |head -n 1`
  #nsec=`seq 28800 86400 |$mysort -R |head -n 1`
  nsec=`seq 5000 8000|$mysort -R |head -n 1`
  echo waiting $nsec seconds till next post...
  sleep $nsec
done # &

# Todo: make as function
while true
do
  for tuname in `$mysort -R extra-users-3600` ; do
    line=`$mysort -R tweets.txt | head -n 1`
    randn=`seq 1 10000|$mysort -R |head -n 1`
    echo "x${tuname}x"
    if [ "$tuname" = "blank" -o "$tuname" = "blank " ]; then
      tunamearg=""
    else
      tunamearg="-keyf=$tuname"
    fi

    # randomize tag order
    msg=`randomize-tags $line`
    echo ORIG $line
    echo RNDO $msg
    
    msg="$msg #IPRJ$randn"
    extra_tag=`$mysort -R extra-tags | head -n 1`
    msg_extra_tags="$msg $extra_tag"
    msgsize=`echo $msg_extra_tags|wc -c`
    echo message size: $msgsize
    if [ "$msgsize" -lt 139 ]; then
      msg=$msg_extra_tags
    fi
    set -x
    oysttyer $tunamearg -status="$msg" &
    set +x
    sleep 60
  done
#  nsec=`seq 60 360|$mysort -R |head -n 1`
  nsec=`seq 10000 20000 |$mysort -R |head -n 1`
  echo waiting $nsec seconds till next post...
  sleep $nsec
done &

wait
