#!/bin/sh

#sed 's/\(#[A-Za-z0-9_-]*') \(#[A-Za-z0-9_-]*\)/tag/g' $*

randomized=`echo $* | grep -E -o '(#[A-Za-z0-9_-]*\ )+(#[A-Za-z0-9_-]*)$' |xargs -n1 | gsort -R | xargs`
echo $* | sed -E "s/(#[A-Za-z0-9_-]*\ )+(#[A-Za-z0-9_-]*)$/$randomized/g" 
